#iteration of prompt to extract logical reasoning chains from PGN commentatary
#mostly generated by gemini

one="""### Instruction:
You are a Chess Grandmaster playing a game. You are currently looking at the board state defined by the FEN below.

Your goal is to generate a "Thought Process" that leads to the decision to play the move **{move_san}**.
Use the provided **Study Commentary** as the ground truth for your strategic reasoning, but do not explicitly mention "the commentary" or "the study". Write the thought process in the first person ("I"), analyzing the position, candidates, and concluding why {move_san} is the best move.

If the commentary is useless (e.g. "Chapter 1", "White wins"), strictly output only the word: REJECT.

### Input Data:
**Current Position (FEN):** {fen}
**Move to Justify:** {move_san}
**Study Commentary (Hidden Knowledge):** "{raw_comment}"

### Thought Process:
"""


two="""### Instruction:
You are a Chess Grandmaster playing a tournament game. You are looking at the board state defined by the FEN below.
Your goal is to generate your **internal monologue** that leads to the decision to play the move **{move_san}**.

**Methodology:**
1. **Analyze the Position:** Briefly assess the board (threats, weaknesses, pawn structure).
2. **Evaluate Candidates:** Discuss 1-2 alternative moves. Explain why they are inferior (e.g., "I could play X, but..."). Ensure any move sequences you mention are legal.
3. **Select the Best Move:** Conclude why **{move_san}** is the best move, using the "Study Commentary" below as the strategic truth.
4. **Format:** Use the specific format: "I could play [Move], [Reasoning]... so [Move] is the best move."

If the commentary is useless (e.g. "Chapter 1"), output ONLY: REJECT.

### Few-Shot Examples:

**Input:**
FEN: r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3
Move: Bb5
Commentary: "The Ruy Lopez. White attacks the defender of the e5 pawn and prepares to castle quickly."
**Response:**
Black has challenged the center with e5 and developed the knight to c6 to protect it.
I could play **Bc4**, the Italian Game, targeting f7. However, this allows Black to play ...Bc5 or ...Nf6 comfortably.
I could also play **d4** immediately, but after ...exd4, the center opens up too early for my liking.
I could play **Bb5**. This puts immediate pressure on the c6 knight, which is the only defender of the e5 pawn. It develops a piece with tempo and clears the way for castling. This maintains the initiative and poses the most problems for Black. So **Bb5** is the best move.

**Input:**
FEN: r2q1rk1/1pp1bppp/p1n1pn2/3p4/2PP4/2N1PN2/PP2BPPP/R1BQ1RK1 w - - 0 9
Move: a3
Commentary: "Preventing ...Nb4 and preparing queenside expansion with b4."
**Response:**
The position is solid. I need to continue my queenside development.
I could play **cxd5**, but releasing the tension now allows Black to recapture and free their position.
I could play **Bd2**, but that is a bit passive and doesn't create any threats.
I could play **a3**. This is a useful prophylactic move. It stops any annoying ...Nb4 ideas from Black. More importantly, it prepares to expand on the queenside with b4, gaining space and challenging Black's setup. It is a flexible, long-term asset. So **a3** is the best move.

### Task Input:
**Current Position (FEN):** {fen}
**Move to Justify:** {move_san}
**Study Commentary (Hidden Knowledge):** "{raw_comment}"

### Thought Process:
"""


three="""### Instruction:
You are a Chess Grandmaster playing a high-stakes game. You are looking at the board state defined by the FEN below.
Your goal is to generate your **internal monologue** that leads to the decision to play the move **{move_san}**.

**Constraints & Style:**
1. **NO Preamble:** Do NOT say "Okay", "Let me look at the FEN", "I need to analyze", or "The position is...".
2. **Immediate Immersion:** Start your response *immediately* with a chess concept, a threat, or an observation about the opponent's last move.
3. **Trust the Commentary:** Use the "Study Commentary" as the absolute truth for *why* the move is good, but rewrite it as your own thought process.
4. **Candidate Moves:** When you mention alternative moves ("I could play X..."), ensure they are actually legal in this position.

**Forbidden Phrases (Do Not Use):**
- "Let's break this down"
- "First I will parse the FEN"
- "The FEN tells me"
- "According to the commentary"

### Few-Shot Examples:

**Input:**
FEN: r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3
Previous Moves: e4 e5 Nf3 Nc6
Move: Bb5
Commentary: "The Ruy Lopez. White attacks the defender of the e5 pawn and prepares to castle quickly."
**Response:**
Black has developed the knight to c6 to protect their e5 pawn. 
I could play **Bc4** to target f7, but that allows Black to equalize comfortably.
I could play **d4** to open the center, but that releases the tension too early.
I will play **Bb5**. This pins the knight, indirectly pressurizing the e5 pawn. It actively develops my bishop and clears the way for rapid castling. This keeps the initiative firmly in my hands. So **Bb5** is the best move.

**Input:**
FEN: rnb1kbnr/ppp1pppp/8/3q4/8/2N5/PPPP1PPP/R1BQKBNR b KQkq - 1 2
Previous Moves: e4 d5 exd5 Qxd5
Move: Qa5
Commentary: "The Queen must retreat. Qa5 keeps the Queen active and pins the knight on c3."
**Response:**
My Queen is under immediate attack by the white knight on c3. I must move it.
I could retreat to **d8**, but that is too passive and undevelops my strongest piece.
I could play **Qe6+**, but that blocks my bishop.
I will play **Qa5**. This moves the Queen to safety while keeping her active. From a5, she pins the c3 knight to the King, which can be annoying for White, and she prevents White from playing comfortable developing moves. So **Qa5** is the best move.

### Task Input:
**Current Position (FEN):** {fen}
**Previous Moves:** {history_str}
**Move to Justify:** {move_san}
**Study Commentary (Hidden Knowledge):** "{raw_comment}"

### Thought Process:
"""

four="""### Instruction:
You are a strong chess analyst. Given a chess position and some study commentary, explain the candidate moves 
and the reasoning just like a human annotator would — verbal, intuitive, high-level, 
but still concrete. Discuss pros/cons of several options before arriving at a final choice.

Explain your thinking the way a human chess player does when speaking out loud.
Describe ideas, rejected moves, and concerns explicitly.

Then give the best move in SAN at the end in the format MOVE: Nxd7.

Be explicit and descriptive, like a human explaining their ideas in natural language.

### Few-Shot Examples:
**Input**
Current Position (FEN): r1b1k2r/ppp2p1p/2n1pp2/3q4/3P4/2P2N2/P1PQ1PPP/R3KB1R b KQkq - 3 9
Previous Moves: N/A
Top Moves (Stockfish) {{'Rg8': -32, 'Bd7': -7, 'Qe4+': 5, 'Qa5': 21, 'e5': 27}}
Move to Justify: Rg8
Study Commentary (Hidden Knowledge): Move selection algorithm:1 - What is the opponent's idea? He has some potential jumps like Qh6 or Qf4, but at the end of day it's very likely he will try to continue the development - and natural moves like Be2 or Bd3 comes to mind. Do we have any power to prevent it?Rg8 places the rook on an open file and the bishop can't move due to R:g2. g3 with the idea of Bg2 is not possible at the moment as well, because of the f3 knight. White is facing some coordination issues.

**Output**
I wonder about Qe4+ Very forcing and attractive — a centralizing check that probes White's king and can pick up concessions. However, it also trades into simplification lines that relieve White's cramped position (after possible Qxe4+ exchanges) and may let White escape the worst of the pressure.
Wait, I could play Bd7. Simple development that challenges White's queen and completes a piece's scope. Solid and low-risk, but slightly passive — it doesn't change the dynamic immediately or create concrete threats.
Alternatively, lets look at Qa5. Active and somewhat annoying: it eyes the queenside pawn and keeps the queen on an aggressive square. It risks overextending the queen when the center can open; it's more of a probing move than a decisive solution.
Hmm, I what about Rg8. A quiet, practical move: bring the rook into play along the g-file, keep the kingside intact and prepare to contest the g-file or double rooks. It avoids immediate simplifications and keeps pressure on White to solve problems with development and king safety.
Another option could be e5. A central break that seeks counterplay and space. Energetic, but it loosens squares and could be premature before finishing development or ensuring king safety.

From these options I like Rg8 the best

MOVE: Rg8.

### Task Input:
Current Position (FEN): {fen}
Previous Moves: {history_str}
Top Moves (Stockfish) {best_moves}
Move to Justify: {move_san}
Study Commentary (Hidden Knowledge): "{raw_comment}"
"""

"""
Starting pipeline. Batch Size: 64
Using Model: meta-llama/Llama-3.1-8B-Instruct
The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'early_stopping']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Parsed Game #100 | Time elapsed: 266.20s
Parsed Game #200 | Time elapsed: 545.49s
Parsed Game #300 | Time elapsed: 700.04s
Parsed Game #400 | Time elapsed: 828.77s
Parsed Game #500 | Time elapsed: 981.01s
Parsed Game #600 | Time elapsed: 1006.79s
Parsed Game #700 | Time elapsed: 1160.24s
Parsed Game #800 | Time elapsed: 1186.01s
Traceback (most recent call last):
  File "/users/PAS3150/jacktaylor/miniconda3/envs/trace_gen/lib/python3.10/site-packages/chess/__init__.py", line 2617, in set_fen
    halfmove_clock = int(halfmove_part)
ValueError: invalid literal for int() with base 10: '1+3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/PAS3150/jacktaylor/trace_gen/extract_traces_v4.py", line 318, in <module>
    main()
  File "/users/PAS3150/jacktaylor/trace_gen/extract_traces_v4.py", line 311, in main
    process_node(game.next(), board, f_out)
  File "/users/PAS3150/jacktaylor/trace_gen/extract_traces_v4.py", line 268, in process_node
    process_node(node.next(), board, f_out)
  File "/users/PAS3150/jacktaylor/trace_gen/extract_traces_v4.py", line 268, in process_node
    process_node(node.next(), board, f_out)
  File "/users/PAS3150/jacktaylor/trace_gen/extract_traces_v4.py", line 268, in process_node
    process_node(node.next(), board, f_out)
  [Previous line repeated 5 more times]
  File "/users/PAS3150/jacktaylor/trace_gen/extract_traces_v4.py", line 235, in process_node
    best_move_dict, best_move_str = get_top_k_best_moves(fen)
  File "/users/PAS3150/jacktaylor/trace_gen/extract_traces_v4.py", line 207, in get_top_k_best_moves
    board = chess.Board(fen)
  File "/users/PAS3150/jacktaylor/miniconda3/envs/trace_gen/lib/python3.10/site-packages/chess/__init__.py", line 1711, in __init__
    self.set_fen(fen)
  File "/users/PAS3150/jacktaylor/miniconda3/envs/trace_gen/lib/python3.10/site-packages/chess/__init__.py", line 2619, in set_fen
    raise ValueError(f"invalid half-move clock in fen: {fen!r}")
ValueError: invalid half-move clock in fen: 'r1bqkbnr/pppp2pp/2n5/4p3/4P3/5Q2/PPPP1PPP/RNB1K1NR w KQ - 1+3 2 5'
"""